pretraining_run_name: None
pretraining_opt_steps: null

#Experiment parameters
random_seed: 13
notes: "Finetuning run"

# Encoder parameters
task_name: "forecasting" 

# Model parameters
model_name: "TraceEncoder"
data_name: health
# overridden by the pretraining run name
seq_len_channel: 192
patch_len: 1  # be overridden by the pretraining run name
patch_stride_len: 1
revin_affine: False
d_model: 384    #384, 768 or 1024
dropout: 0.1
n_heads: 6
e_layers: 6
attention_dropout: 0.1
torch_dtype: "bfloat16"
value_embedding_bias: False # Whether to add biases to the value embeddings
orth_gain: 1.41
pos_embed_type: "rel_pos" # "rope" or "rel_pos" add positional embedding to the input
set_input_mask: True # Whether to set the input mask
output_attention: False # Whether to output the attention weights
activation: 'gelu'      # "gelu" or "relu"
flash_attention: False
use_temporal_prior: true
use_prior_calibrated_logits: true
use_time_conditioned_alignment: true
lambda_time_align: 0.1
time_align_temperature: 0.07
prior_hidden_dim: 128
prior_input_dim: null
domain_emb_dim: 32
num_domains: 10
prior_alpha: 0.1
prior_beta: 0.1
prior_dropout: 0.1
use_text_gated_forecast: false
text_residual_alpha: 0.05
use_direct_text_forecast: true
text_data_path: null
text_date_col: date
text_col: text
text_encoder_type: offline_embedding
text_embedding_path: null
text_emb_dim: 768
freeze_text_encoder: true
text_fusion_type: gated_residual
lookback_text_window: null
use_text_leakage_check: true
use_month: true
use_season: true
use_day_of_year: true
use_weekday: true
use_solar_term: false
domain_name: Agriculture
use_prior_guided_hard_negative: false


# Logging
log_interval: 1
checkpoint_interval: 1
debug: False

# Training parameters
finetuning_mode: "linear-probing" # "linear-probing" "end-to-end"

mask_ratio: 0.3
max_epoch: 100
optimizer_name : "AdamW"
enable_gradient_checkpointing: True
max_norm: 5
weight_decay: 0.05
lr_scheduler_type: 'linearwarmupcosinelr' # "onecyclelr" "linearwarmupcosinelr"
pct_start: 0.3
init_lr: 0.001
min_lr: 0.00001 # 1e-5
lr_decay_rate: 0.9
warmup_lr: 0.00001 # 1e-5
warmup_steps: 1000
use_amp: True
beta: 1
distributed: True
early_stop: False
patience: 50
delta: 0.001



# Dataset parameters
forecast_horizon: 6
n_channels: 7
scale : True
upsampling_pad_direction : "backward"
upsampling_type : "pad"
downsampling_type : "interpolate"
pad_mode : "constant"
pad_constant_values : 0
train_batch_size : 32 # 1024 2048 3072 4096
val_batch_size: 32 # 1024 2048 3072 4096 
shuffle : True
num_workers : 5
pin_memory : True
drop_last : False
